// svelte/react/src/App.js
import React from "react";
import "./App.css";
import { AddTransaction } from "./components/AddTransaction";
import { Balance } from "./components/Balance";
import { Header } from "./components/Header";
import { IncomeExpenses } from "./components/IncomeExpenses";
import { TransactionList } from "./components/TransactionList";
import { GlobalProvider } from "./context/GlobalState";

function App() {
  return (
    <GlobalProvider>
      <Header />
      <div className="container">
        <Balance />
        <IncomeExpenses />
        <TransactionList />
        <AddTransaction />
      </div>
    </GlobalProvider>
  );
}

export default App;

// svelte/svelte/src/App.svelte
<script>
  import Balance from "./components/Balance.svelte";
  import IncomeExpenses from "./components/IncomeExpenses.svelte";
  import TransactionList from "./components/TransactionList.svelte";
  import AddTransaction from "./components/AddTransaction.svelte";
  import { hydrateStore } from "./util/service";
  import { onMount } from "svelte";

  onMount(hydrateStore);
</script>

<main>
  <h2>Expense Tracker</h2>
  <div class="container">
    <Balance />
    <IncomeExpenses />
    <TransactionList />
    <AddTransaction />
  </div>
</main>
